import asyncio
from nats.aio.client import Client as NATS
from nats.aio.errors import ErrConnectionClosed, ErrTimeout, ErrNoServers

async def connect_to_server(nats_client):

    await nc.connect("localhost:4222")

async def msg_handler(msg):
    subject = msg.subject
    reply = msg.reply
    data = msg.data.decode()
    print('Received a message on {:s}: reply = {:s}, data = {:s}'.format(
        subject, reply, data))

async def main():

    # Create NATS client object and connect to server.
    nc = NATS()
    await connect_to_server(nc)

    # Subscribe to same channel on which I'll publish.
    sid = await nc.subscribe('foo', cb=msg_handler)

    await nc.publish('foo', b'Hello')
    await nc.publish('foo', b'World')

    # Close nats client connection.
    await nc.close()


if __name__ == '__main__':

    asyncio.run(main(), debug=True)
